# Usamos Nginx como servidor web
FROM nginx:alpine

# Copiamos nuestro hermoso index.html a la carpeta pública de Nginx
COPY index.html /usr/share/nginx/html/index.html

# Exponemos el puerto 80 (puerto web por defecto)
EXPOSE 80