version: '3.8'

services:
  backend-banco:
    image: ${DOCKER_USERNAME}/aws-banco-backend:latest
    networks:
      - red_bancaria
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  frontend-banco:
    image: ${DOCKER_USERNAME}/aws-banco-frontend:latest
    networks:
      - red_bancaria
    ports:
      - "80:80"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  red_bancaria:
    driver: overlay