version: '3.8'

services:
  # SERVICIO 1: Backend
  backend-banco:
    image: tu_usuario_dockerhub/aws-banco-backend:latest
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]
    networks:
      - red_bancaria
    env_file:
      - .env

  # SERVICIO 2: Frontend
  frontend-banco:
    image: tu_usuario_dockerhub/aws-banco-frontend:latest
    ports:
      - "80:80"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - red_bancaria
    depends_on:
      - backend-banco

networks:
  red_bancaria:
    driver: overlay